name: CI

on:
  push:
    branches:
      - "master"
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  # REGISTRY是空就推送到官方仓库
  REGISTRY: ''
  GRADLEW_IMAGE_NAME: 'maa-backend-center'
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
  TAG_SHA: ${{ github.sha }}
  TAG_LATEST: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #checkout代码
      - uses: actions/checkout@v4
      #安装graalvm
      - name: 安装graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '21'
      #查看版本信息
      - name: 查看版本信息
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      #校验Gradle wrapper
      - name: 校验Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      #使用Gradle编译项目
      - name: 使用Gradle编译项目
        uses: gradle/gradle-build-action@v3
        with:
          arguments: bootBuildImage

      # 登录docker仓库
      - name: 登录docker仓库 ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #直接推送
      - name: Push docker image to DockerHub
        run: |
          docker tag ${{env.GRADLEW_IMAGE_NAME}} ${{env.IMAGE_NAME}}:v${{env.TAG_SHA}}
          docker tag ${{env.GRADLEW_IMAGE_NAME}} ${{env.IMAGE_NAME}}:${{env.TAG_LATEST}}
          docker rmi ${{env.GRADLEW_IMAGE_NAME}}
          docker push --all-tags ${{env.IMAGE_NAME}}